# Welcome to Serverless!

service: deeplens-doorman

provider:
  name: aws
  runtime: python3.7

  # you can overwrite defaults here
  stage: demo

  region: ap-northeast-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:SearchFacesByImage"
        - "rekognition:IndexFaces"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"

  # you can define service wide environment variables here
  environment:
    AWSREGION: ${env:AWSREGION}
    BUCKET_NAME: ${env:BUCKET_NAME}

functions:
  # find person, function for greengrass device
  find-person:
    handler: find_person.function_handler

plugins:
  - serverless-python-requirements
